# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Personal Page
email: warriorlance@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a Controls Physicist in the research field of accelerator. I have PhD
  on free-electron laser (Doctor of Engineering), I'm skilled at high-level
  controls. This site keeps my notes and geekstuff related to my work, like
  projects building with Python, C/C++, MATLAB, etc., or lessons learnt,
  memos/notes, ... to keep myself moving forward.
baseurl: # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site
github_username:  archman

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
